## Importing Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Loading Dataset

I don't have dataset so i am creating some random data.

In [2]:
import random
import pandas as pd

import random
import pandas as pd

# Set the number of rows to generate
num_rows = 300

# Create empty lists to store the data
age = []
salary = []
status = []

# Generate random data for each column
for i in range(num_rows):
    # Determine age group based on age
    if i < num_rows * 0.1:
        age_group = 'child'
        salary_range = (0, 3000)
    elif i < num_rows * 0.3:
        age_group = 'teen'
        salary_range = (3000, 10000)
    elif i < num_rows * 0.6:
        age_group = 'less young'
        salary_range = (10000, 20000)
    elif i < num_rows * 0.8:
        age_group = 'moderate adult'
        salary_range = (20000, 40000)
    else:
        age_group = 'good with increase in age'
        salary_range = (40000, 80000)
    
    # Calculate salary based on age group
    age.append(random.randint(10, 100))
    salary.append(random.randint(*salary_range))
    
    # Determine status based on age group
    if age_group in ['child', 'teen']:
        status.append(0)
    else:
        status.append(1)

# Create a dictionary to store the data
data = {'age': age, 'salary': salary, 'status': status}

# Convert the dictionary to a Pandas DataFrame
df = pd.DataFrame(data)

# Display the first 5 rows of the DataFrame
print(df.head())

   age  salary  status
0   26    2902       0
1   44    2515       0
2   46    2793       0
3   46    2617       0
4   51    2873       0


## Summarize Dataset

In [3]:
df.shape

(300, 3)

In [4]:
df.isnull().sum()

age       0
salary    0
status    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     300 non-null    int64
 1   salary  300 non-null    int64
 2   status  300 non-null    int64
dtypes: int64(3)
memory usage: 7.2 KB


In [6]:
df.describe()

age        salary      status
count  300.000000    300.000000  300.000000
mean    54.906667  24030.186667    0.700000
std     27.033695  20939.433496    0.459023
min     10.000000    308.000000    0.000000
25%     30.000000   8621.250000    0.000000
50%     54.000000  16792.500000    1.000000
75%     76.000000  34539.250000    1.000000
max    100.000000  79971.000000    1.000000

## Segregating Dataset into X & Y

In [7]:
X = df.iloc[:,:-1].values
X

array([[   26,  2902],
       [   44,  2515],
       [   46,  2793],
       [   46,  2617],
       [   51,  2873],
       [   54,  1385],
       [   12,  2889],
       [   42,   389],
       [   95,   374],
       [   10,  1503],
       [   81,  2663],
       [   94,  1598],
       [   14,  2203],
       [   86,  2610],
       [   95,   308],
       [   65,   388],
       [   91,  1953],
       [   24,  1546],
       [   69,  1184],
       [   99,  1174],
       [   75,  1296],
       [   17,   946],
       [   95,  2590],
       [   56,  2010],
       [   51,  2726],
       [   63,  2064],
       [   25,   941],
       [   55,  2264],
       [   13,  1534],
       [   86,  1949],
       [   84,  7036],
       [   90,  4680],
       [   69,  9191],
       [   13,  8050],
       [   37,  6583],
       [   72,  7605],
       [   93,  6952],
       [   44,  8433],
       [   21,  5349],
       [   30,  9523],
       [   85,  5292],
       [   67,  9105],
       [   45,  3008],
       [   

In [8]:
Y = df.iloc[:,-1].values
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], d

## Splitting Dataset into Train and Test

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-1.48574956,  2.5233488 ],
       [-0.43261925, -0.7543656 ],
       [-0.65829003, -0.55384246],
       [-0.01888948,  0.08118708],
       [ 0.31961669, -0.57979308],
       [-0.09411307, -0.29433634],
       [-0.05650128, -0.53240707],
       [-0.92157261,  1.82524882],
       [ 0.58289927,  0.48275616],
       [ 0.35722849,  0.06897223],
       [ 0.77095826, -0.9696226 ],
       [ 0.43245208, -0.19476394],
       [ 0.47006388,  0.1615104 ],
       [ 0.62051107,  2.3742516 ],
       [ 1.59841779,  0.50024669],
       [-0.35739565,  1.49977301],
       [-1.26007878, -0.78117173],
       [ 0.2820049 ,  0.93570366],
       [ 1.03424083, -0.2035092 ],
       [ 1.37274701, -0.21852824],
       [ 0.13155771, -0.62561064],
       [ 1.63602958, -0.35407978],
       [-1.48574956, -0.71824387],
       [-0.20694846, -0.11605659],
       [ 0.50767568, -1.09890037],
       [ 0.05633411,  1.55699744],
       [-0.24456026,  1.39459223],
       [ 0.88379365, -0.46163699],
       [-0.73351362,

## Training

In [11]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [12]:
model.fit(X_train,y_train)

LogisticRegression()

## Predicting For Test Data

In [13]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [14]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]]


## Accuracy

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix")
print(cm)

Confusion Matrix
[[21  1]
 [ 1 52]]


In [16]:
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.9733333333333334
